### ISSUE TITLE
Migrated files coexist in both repos (Relay to www-l10n)

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/fx-private-relay-l10n#162]
Three files that should have been migrated to mozilla.org are still present in this repo. 

**mozilla.org PR**: https://github.com/mozilla-l10n/www-l10n/pull/343/files 
- bundle.ftl: https://github.com/mozilla-l10n/www-l10n/pull/343/files#diff-8966c366abceb1727c1e5f171e56e490797baa2719bd679e29a6d3bb6d54f7b3
- faq.ftl: https://github.com/mozilla-l10n/www-l10n/pull/343/files#diff-a617b74d170c8375485bff2e399d261dfa46590509dfbb3bdbcbfc105df98363
- landing.ftl: https://github.com/mozilla-l10n/www-l10n/pull/343/files#diff-1c5847a6063aec213cf13a8ae88825f749b29428f53e2d5cf27dbe8db783dc27

**Relay Repo**
- bundle.ftl: https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/main/en/bundle.ftl
- faq.ftl: https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/main/en/faq.ftl
- landing.ftl: https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/main/en/landing.ftl

**Relay l10n.toml** file update: https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/154 shows to have removed the `faq` and `landing` entries. 

There needs to be an extra step to remove the `en` files and maybe an extra step to remove the localized files.  

Pontoon shows correctly how it's defined in the `l10n.toml`  file

**Comment by flodolo** [comment]
@bcolsson 
My understanding is that these files were left there on purpose, because still needed while migrating?

**Comment by bcolsson** [comment]
@flodolo @peiying2 - Correct, these are still there because the Relay site on firefox.com is stil live. I'm following-up again about when the migration is going to be complete. Last time I asked in the migration slack channel and got crickets, so following up with Stephanie to hopefully get a better picture of what's going on.

**Comment by groovecoder** [comment]
I'm afraid we have to close this without any action? :/ The translation files in the www repo look like they are split into different filenames (fine) with different string IDs (not fine 😢 ).
