### ISSUE TITLE
`$subdomein` typo in `nl` file is causing FTL exceptions

### ISSUE THREAD

**Issue by groovecoder** [mozilla-l10n/fx-private-relay-l10n#40]
https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/ce1b9d98672589c357c26c796d5a96df8a10829a/nl/app.ftl#L476

is causing: https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/11770350/activity/?query=is%3Aunresolved

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla-l10n/fx-private-relay-l10n/commit/8731e8ca4b910b704c1f0351505450a1680f0365.

**Comment by peiying2** [comment]
This is fixed.
