### ISSUE TITLE
Misprints in the strings

### ISSUE THREAD

**Issue by denisgon** [mozilla-l10n/fx-private-relay-l10n#71]
There are several misprints in the strings of the project:

- strings 236760 (deprecated: «Trying to sign up for discounts without all the spam? Bundle all your “shopping” accounts under unique custom aliases, like “mydeals@mydomain.mozmail.com.”») and 243309 («Trying to sign up for discounts without all the spam? Bundle all your “shopping” accounts under custom email masks, like “mydeals@mydomain.mozmail.com.”»): the fullstop should go after the quote in the end of the strings;
- strings 233376 (deprecated: «Why did my aliases start to use the domain “mozmail.com?”») and 243378 («Why did my email masks start to use the domain “mozmail.com?”»): the question mark should go after the quote in the end of the strings.

**Comment by Vinnl** [comment]
Hi @denisgon, I checked in with our content specialist, and apparently the style where punctuation is inside the quotation marks is American English, whereas they're usually outside of the quotes in British English. The default product language is in American English, but the British English localisation (and others, of course) can change these if so desired. (And for completeness sake: localisations are [managed in Pontoon](https://pontoon.mozilla.org/projects/firefox-relay-website/), where localisations can be contributed.)

**Comment by denisgon** [comment]
@Vinnl, thank you. I didn't know about such feature of American English. Then everything is OK.
